server:
  port: 8088

spring:
  application:
    name: order-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

  config:
    import:
      - "configserver:"  # Đặt trong danh sách và dùng dấu ngoặc kép

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/