spring:
  application:
    name: order-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: "configserver:"  # Sửa lại thành chuỗi thay vì dạng danh sách

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
