spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

  config:
    import:
      - "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
