spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

  config:
    import:
      - "optional:configserver:"  # Đặt trong danh sách và dùng dấu ngoặc kép

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
